server:
  port: 8082

propery_owner: 'local property local'

#kafka_server_ip: ${KAFKA_SERVER_IP}
#kafka_server_port: ${KAFKA_SERVER_PORT}
kafka_server_ip: 192.168.1.100
kafka_server_port: 9092

spring:
  application:
    name: msa-service-coffee-order
  h2:
    console:
      enabled: true
      path: /h2console
  datasource:
    driver-class-name: org.h2.Driver
    #url: jdbc:h2:file:~/h2/msa-service-coffee-order
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  cloud:
    config:
      discovery:
        enabled: true
        service-id: 'msa-architecture-server-config' #update -> curl -X POST http://localhost:8081/actuator/refresh
  kafka:
    producer:
      bootstrap-servers:

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'

#Eureka Client
eureka:
  client:
    serviceUrl:
      #defaultZone: http://${EUREKA_SERVER_IP}:9091/eureka/
      defaultZone: http://localhost:9091/eureka/
    enabled: true
  instance:
    preferIpAddress: true
    instance-id:


logging:
  path: logs
  level:
    org.springframework: INFO
    org.springframework.web: DEBUG
    com.minji.msa.zuul.system: DEBUG
    com.minji.msa.zuul.springboot: DEBUG